/**
 * Generates an initial AGENT_RULES.md master file based on detected project metadata.
 * @param {object} metadata
 * @param {object|null} pkg
 * @returns {string}
 */
export function generateMasterTemplate(metadata, pkg = null) {
  const pm = metadata.packageManager;
  const langs = metadata.languages.length > 0 ? metadata.languages.join(', ') : 'JavaScript / TypeScript';
  const frameworks = metadata.frameworks.length > 0 ? metadata.frameworks.join(', ') : 'Standard library / Custom';
  const testCmd = metadata.testRunner
    ? `${pm === 'npm' ? 'npm test' : `${pm} test`}`
    : `${pm === 'npm' ? 'npm test' : `${pm} test`} (configure if needed)`;

  const buildCmd = pkg?.scripts?.build
    ? `${pm === 'npm' ? 'npm run build' : `${pm} run build`}`
    : `${pm} run build`;

  const lintCmd = metadata.lintFormatters.length > 0
    ? `${pm === 'npm' ? 'npm run lint' : `${pm} run lint`}`
    : 'None configured';

  return `# AGENT_RULES.md
<!-- Generated by agentrules (https://github.com/vijay/agentrules) -->
<!-- Edit this master file, then run 'npx agentrules sync' to update all AI assistant configurations -->

## Project Overview
- **Languages**: ${langs}
- **Frameworks**: ${frameworks}
- **Package Manager**: ${pm}
- **Test Runner**: ${metadata.testRunner || 'Not detected'}

## Critical Workflow Commands
- **Install Dependencies**: \`${pm === 'npm' ? 'npm install' : `${pm} install`}\`
- **Build / Bundle**: \`${buildCmd}\`
- **Run Tests**: \`${testCmd}\`
- **Lint / Format**: \`${lintCmd}\`

## Coding Standards & Architectural Guidelines
1. **Consistency**: Follow idiomatic patterns established in the existing codebase.
2. **Type Safety**: Maintain strict types where TypeScript is enabled. Avoid using \`any\`.
3. **Modularity**: Write focused, testable, single-responsibility functions and modules.
4. **Dependencies**: Prefer native Node/web APIs where feasible before introducing heavy external dependencies.
5. **Testing**: Always add or update unit tests when modifying core logic. Ensure all tests pass before completing changes.

## Agent Behavior & Restrictions
- Do not make breaking changes to public APIs without explicit instructions.
- Do not commit secrets, API keys, or private environment variables.
- Keep comments concise and focused on "why" rather than "what".
- Verify test suites pass locally after applying edits.
`;
}
